# Generated by Django 6.0.3 on 2026-04-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='file_url',
            field=models.TextField(),
        ),
    ]
