services:
  - type: web
    name: pdf-organizer
    env: python
    buildCommand: |
      # 1. Build Frontend
      cd frontend && npm install && npm run build
      
      # 2. Build Backend and Dependencies
      cd .. && pip install -r requirements.txt
      cd backend
      python manage.py collectstatic --no-input
      python manage.py migrate
      python seed_db.py
    startCommand: gunicorn --chdir backend backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: VITE_SUPABASE_URL
        value: https://yobxelhmjljcwxggitot.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvYnhlbGhtamxqY3d4Z2dpdG90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0NzQxODUsImV4cCI6MjA5MTA1MDE4NX0.nM-wT5vAwd3g6aRXv6eO3zv9On8UFuhkLn_8kohMwCw
      - key: VITE_API_URL
        value: /api

